name: on-push-run-tests
on:
  push:
    branches:
      - '*'
    tags:
      - '![0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Run Tests
        run: dotnet test -c Release
