name: on-tag-do-release
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  release:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version=${{ github.ref_name }} --no-restore
      - name: Test
        run: dotnet test -c Release --no-restore --no-build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: src\nugets\*.nupkg
      - name: Push Nuget
        run: dotnet nuget push nugets\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
